import { defineConfig } from 'vitest/config'

export default defineConfig({
  resolve: {
    tsconfigPaths: true,
  },
  test: {
    environment: 'jsdom',
    include: ['src/**/*.test.{ts,tsx}'],
    exclude: ['**/node_modules/**', '**/routeTree.gen.ts', '**/*.d.ts'],
    pool: 'forks',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.test.{ts,tsx}',
        'src/**/*.spec.{ts,tsx}',
        'src/routeTree.gen.ts',
        'src/**/*.d.ts',
        'src/db/schema.ts',
        'src/router.tsx',
        'src/routes/**',
        'src/lib/GoogleTraslation.ts',
        'src/lib/MicrosoftTranslation.ts',
        'src/lib/db.ts',
        'src/lib/translationDb.ts',
        'src/lib/translate.ts',
        'src/lib/translate.types.ts',
        'src/lib/rateLimit.ts',
        'src/components/icons/**',
        'src/components/ui/**',
        'src/components/word-cloud-options/**',
        'src/components/Footer.tsx',
        'src/components/Header.tsx',
        'src/components/IslandPanel.tsx',
        'src/components/LinkButton.tsx',
        'src/components/NavLink.tsx',
        'src/components/PageHero.tsx',
        'src/components/SourceTextPanel.tsx',
        'src/components/TextareaField.tsx',
        'src/components/ThemeToggle.tsx',
        'src/hooks/useWordCloudLayout.ts',
        'src/components/WordCloudOptions.tsx',
        'src/components/WordCloudCanvas.tsx',
      ],
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
    },
  },
})
