/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as TextCloudRouteImport } from './routes/text-cloud'
import { Route as IndexRouteImport } from './routes/index'

const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const TextCloudRoute = TextCloudRouteImport.update({
  id: '/text-cloud',
  path: '/text-cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/text-cloud': typeof TextCloudRoute
  '/translate': typeof TranslateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/text-cloud': typeof TextCloudRoute
  '/translate': typeof TranslateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/text-cloud': typeof TextCloudRoute
  '/translate': typeof TranslateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/text-cloud' | '/translate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/text-cloud' | '/translate'
  id: '__root__' | '/' | '/text-cloud' | '/translate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TextCloudRoute: typeof TextCloudRoute
  TranslateRoute: typeof TranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-cloud': {
      id: '/text-cloud'
      path: '/text-cloud'
      fullPath: '/text-cloud'
      preLoaderRoute: typeof TextCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TextCloudRoute: TextCloudRoute,
  TranslateRoute: TranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
